name: Release to Github and jsDeliver

on: 
  push:
    tags:
      - 'v*.*.*' # Trigger on version tag, e.g., v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build the library
        run: npm run build:prod # Ensure your build command is in package.json

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: 'dist/**/*' # Adjust to your output folder

      - name: Post-release cleanup
        run: echo "Relese complete"
