name: Release

on: 
  push:
    tags:
      - 'v*.*.*' # Trigger on version tag, e.g., v1.0.0
  workflow_dispatch:  # Allows manual triggering

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Update package.json version
        uses: adobe/update-prerelease-npm-version@v1.2.0
        with:
          pre-release-tag: 'pre'

      # Show the updated package.json for verification
      - name: Show Updated Version
        run: cat package.json

      - name: Publish to npm (next tag)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --tag next --access public

      - name: Publish Final Version to npm
        if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access public

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: 'dist/**/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

