name: Release

on: 
  push:
    tags:
      - 'v*.*.*' # Trigger on version tag, e.g., v1.0.0
  workflow_dispatch:  # Allows manual triggering

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Build the Project
        run: npm run build # Ensure this outputs to the dist directory

      - name: Update Pre-release Version
        if: "!startsWith(github.ref, 'refs/tags/v')"
        run: |
          # Increment the pre-release version using npm version
          npm version prerelease --preid=next -m "Automated pre-release version bump to %s"
          cat package.json  # Show the updated version for verification

      - name: Publish Pre-release Version to npm (next tag)
        if: "!startsWith(github.ref, 'refs/tags/v')" # Run only for pre-release versions
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish dist --tag next --access public

      - name: Increment Version and Publish Final
        if: startsWith(github.ref, 'refs/tags/v')  # Run only for final versions
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # Automatically bump version based on the GitHub tag
          npm version from-git --no-git-tag-version
          npm publish dist --provenance --access public --tag latest

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')  # Only run if a version tag is pushed
        uses: softprops/action-gh-release@v1
        with:
          files: 'dist/**/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

