name: Release to Github and jsDeliver

on: 
  push:
    tags:
      - 'v*.*.*' # Trigger on version tag, e.g., v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      content: read
      id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
